name: base
version: 0.0.0
homepage: https://github.com/morloc-lib/base
synopsis: Core types across all languages
description: This is totally experimental
category: language-base
license: MIT
author: "Zebulun Arendsee"
maintainer: "zbwrnz@gmail.com"
github: https://github.com/morloc-lib/base
bug-reports: https://github.com/morloc-lib/base
